### PR TITLE
Individual parameters file

### LINKED ISSUE #387: IndividualParameters - individual specific model parameters as part of the "Individuals" file
Combine "IndividualBiometrics" and "IndividualParametrs" to "Individuals".

### PR DESCRIPTION
**Pull request by PavelBal**
Fixes #387

### CODE REVIEW

**Comment by PavelBal** [comment]
@Felixmil Any idea what is going on? Tests are passing locally for `esqlabsR` and for `ospsuite` but failing on AppVeyor, I cannot make any sense of it.

**Comment by Felixmil** [comment]
> @Felixmil Any idea what is going on? Tests are passing locally for `esqlabsR` and for `ospsuite` but failing on AppVeyor, I cannot make any sense of it.

I'm on it. I'm anticipating an dependency's versions difference between appveyor and your local environment but we'll see.

**Comment by Felixmil** [comment]
@PavelBal After installing packages like Appveyor does, I was able to reproduce the errors on my local env.

```r
install.packages(c('covr', 'clipr', 'shinytest2', 'vdiffr', 'withr'), repos = 'http://cran.us.r-project.org')
download.file('https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/ospsuite-rutils/artifacts/ospsuite.utils.zip?pr=false', destfile = 'ospsuite.utils.zip', mode='wb'); install.packages('ospsuite.utils.zip', repos = NULL, type = 'binary')
download.file('https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/tlf-library/artifacts/tlf.zip?pr=false', destfile = 'tlf.zip', mode='wb');  install.packages('tlf.zip', repos = NULL, type = 'binary')
download.file('https://ci.appveyor.com/api/projects/StephanSchaller/esqlabs-parameteridentification/artifacts/ospsuite.parameteridentification.zip?pr=false', destfile = 'ospsuite.parameteridentification.zip', mode='wb', headers = c('Authorization' = 'Bearer v2.4n7xybvbbboj2ye9fmk5')); install.packages('ospsuite.parameteridentification.zip', repos = NULL, type = 'binary')
devtools::test()
```

```r
Failure (test-sensitivity-calculation.R:487:3): sensitivityTimeProfiles plots are as expected for multiple output paths
Snapshot of `testcase` to 'sensitivity-calculation/multiple-output-path-profiles.svg' has changed
Run `testthat::snapshot_review('sensitivity-calculation/')` to review changes
Backtrace:
 1. vdiffr::expect_doppelganger(...)
      at test-sensitivity-calculation.R:487:2
 3. testthat::expect_snapshot_file(...)
 
#...
```

So I guess you have a version of a dependency package that is different than the latest `dev` ones. I'm suspecting {tlf} because of all the breaking changes implemented recently.

**Comment by Felixmil** [comment]
> This is really weird, as I have all packages up to date, and TLF is the latest develop. Really confusing.

Did you try with this locally:
```r
install.packages(c('covr', 'clipr', 'shinytest2', 'vdiffr', 'withr'), repos = 'http://cran.us.r-project.org')
download.file('https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/ospsuite-rutils/artifacts/ospsuite.utils.zip?pr=false', destfile = 'ospsuite.utils.zip', mode='wb'); install.packages('ospsuite.utils.zip', repos = NULL, type = 'binary')
download.file('https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/tlf-library/artifacts/tlf.zip?pr=false', destfile = 'tlf.zip', mode='wb');  install.packages('tlf.zip', repos = NULL, type = 'binary')
download.file('https://ci.appveyor.com/api/projects/StephanSchaller/esqlabs-parameteridentification/artifacts/ospsuite.parameteridentification.zip?pr=false', destfile = 'ospsuite.parameteridentification.zip', mode='wb', headers = c('Authorization' = 'Bearer v2.4n7xybvbbboj2ye9fmk5')); install.packages('ospsuite.parameteridentification.zip', repos = NULL, type = 'binary')
devtools::test()
```

**Comment by PavelBal** [comment]
I suspect this: 
https://github.com/Open-Systems-Pharmacology/TLF-Library/blob/cdbf792b93fb3558fa73950b670840aee9c4c5f0/R/zzz.R#L3

**Pull request merged**
