### PR TITLE
closes #132

### LINKED ISSUE #132: use `{ospsuite.utils}` instead of using internal functions (`:::`) from `{ospsuite}`
https://cran.r-project.org/web/packages/ospsuite.utils/index.html

### PR DESCRIPTION
**Pull request by IndrajeetPatil**

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Need to wait till binaries are built on CRAN.

**Comment by IndrajeetPatil** [comment]
@PavelBal This is ready now! Whenever you can, please have a look.

**Comment by IndrajeetPatil** [comment]
This needs to be merged ASAP because `{esqlabsR}` no longer works with the development version of `{ospsuite}`.

**Comment by PavelBal** [comment]
@IndrajeetPatil As it will be a breaking change, we need to:

merge develop to main
create a release from main
then it can be merged to develop.

**Comment by IndrajeetPatil** [comment]
This is not a braking change. All changes are strictly internal to the package, and none are user-facing.

**Comment by IndrajeetPatil** [comment]
> This is not a braking change

I need to qualify my statement here. Apparently, whether adding a new dependency counts as a breaking change or not is [debatable](https://github.com/semver/semver/issues/502) in semantic versioning, so we might as well take the cautious route and treat this as a breaking change even if API stays the same.

I will update NEWS.

**Comment by IndrajeetPatil** [comment]
@PavelBal See if this looks good now.

**Review by PavelBal — APPROVED** [review]

**Pull request merged**
