### PR TITLE
Move `$outputDevice` to `ProjectConfiguration`

### LINKED ISSUE #238: Increment to v4
After release of v3, create v4 in the develop branch

### LINKED ISSUE #247: Move property `outputDevice` from `ScenarioConfiguration` to `ProjectConfiguration`

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
Closes #247
Closes #238 

- Bump version to the next version
- Clean up NEWS
- Update website docs for the same

### CODE REVIEW

**Comment by PavelBal** [comment]
This must wait for v4 as it will be a breaking change. It is explicitely scheduled for v4 project.

**Comment by IndrajeetPatil** [comment]
> This must wait for v4 as it will be a breaking change.

How can this be a breaking change?! It doesn't exist in the release version of _esqlabsR_.

**Comment by IndrajeetPatil** [comment]
@PavelBal This should be ready for a review now.

**Comment by PavelBal** [comment]
Sorry, just did it in another PR that I will open now.

**Pull request closed without merging**
