### PR TITLE
Long legend

### LINKED ISSUE #503: Fit text into plot size when exporting
When plot titles/subtitles/legend entries etc are too long and do not fit into the figure, there are cropped. Find an automated way to adjust their size (similar to what powerpoint does).

Proposal: ExportConfiguration should re-calculate text size to fit.

### PR DESCRIPTION
**Pull request by PavelBal**
Fixes #503

### CODE REVIEW

**Comment by PavelBal** [comment]
@Felixmil This PR introduces automatic adjustment of text sizes of a plot that is exported through `ExportConfiguration`.

Some test code:

```
###### Test for long captions
myDc <- DataCombined$new()
ds <- DataSet$new("testDs")
ds$setValues(1, 1)
myDc$addDataSets(ds)

myDc2 <- DataCombined$new()
ds2 <- DataSet$new("testssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssDs!")
ds2$setValues(1, 1)
myDc2$addDataSets(list(ds, ds2))

plotConfig <- createEsqlabsPlotConfiguration()
plotConfig$title <- "Even loooooooooooooo00000000000000000000000000000000000000ooooooooooooooonger titleeeeeeee!"
singlePlot <- plotIndividualTimeProfile(myDc, plotConfig)
plotConfig$title <- "plot b"
singlePlot2 <- plotIndividualTimeProfile(myDc2, plotConfig)

plotGridConfiguration <- createEsqlabsPlotGridConfiguration()
plotGridConfiguration$title <- "lssooooooooooooooooooooooo000000000000000000000000000000000000000000000oooon"
plotGridConfiguration$addPlots(list(singlePlot, singlePlot2))

plotCombined <- plotGrid(plotGridConfiguration)

exportConfiguration <- createEsqlabsExportConfiguration(projectConfiguration = projectConfiguration)
exportConfiguration$name <- "testExport"
exportConfiguration$savePlot(plotCombined, autoscaleText = TRUE)
exportConfiguration$savePlot(singlePlot2, autoscaleText = TRUE)
```

Example of a plot with `autoscaleText = FALSE`:

testExport_

The same plot exported with `autoscaleText = TRUE`: 
testExport


Legend entries are still causing lot of trouble, as:

- Symbol size in the legend is too big (much bigger than in the actual plot)
- Symbol size is not scaling with the text. Would it be scaled, the overall shrinking required to fit the text would be smaller and the text could be bigger (and it would be more consistent)
- Spacing between legend entries and between the symbol and the text is too big.

@Felixmil I twisted my brain trying to figure out how to change the size of legend symbols, but I could not figure it out. Maybe you will have better luck. Please try to find ways to change the above-mentioned properties. I could take care of the (initial) fine-tuning.

**Comment by Felixmil** [comment]
@PavelBal If I understood correctly, only the exported version of the plots will have adjusted text/keys sizes, not the plot Object.

Shouldn't we perform these modifications directly in the plot generation processes (plot and grids) so that objects and exports are identical ? If yes, I can move reuse what you implemented here in {tlf}.

**Comment by PavelBal** [comment]
If this can be done at earlier steps than export - even better, go ahead. I wasn't sure because the size of the plot in cm is defined in the export configuration, I am not that familiar with gglop to judge if the scaling can be done earlier.

**Comment by Felixmil** [comment]
Here is what can be obtained with the new TLF branch: 
``` r
library(esqlabsR)
#> Loading required package: ospsuite
#> Loading required package: rClr
#> Loading the dynamic library for Microsoft .NET runtime...
#> Loaded Common Language Runtime version 4.0.30319.42000
    ###### Test for long captions
    myDc <- DataCombined$new()
    ds <- DataSet$new("LegendsCanHaveVeryLongStrings|BecauseTLFNowWrapsThemOn|SpacesorSpecialCharacters")
    ds$setValues(1, 1)
    myDc$addDataSets(ds)
    
    myDc2 <- DataCombined$new()
    ds2 <- DataSet$new("LegendsCanHaveVeryLongStringsBecause|TLFNowWrapsThemOnSpacesorSpecialCharacters")
    ds2$setValues(1, 1)
    myDc2$addDataSets(list(ds, ds2))
    
    plotConfig <- createEsqlabsPlotConfiguration()
    plotConfig$titleSize <- 8
    plotConfig$title <- "ThisPlotTitleIsVeryLong ButTLFCanNowWrapLongStringsOnSpaces WhichShouldBeCommonOnPlotTitles!"
    singlePlot <- plotIndividualTimeProfile(myDc, plotConfig)
    plotConfig$title <-  "ThisPlotTitleIsAlsoVeryLong ButTLFCanNowWrapLongStringsOnSpaces WhichShouldBeCommonOnPlotTitles!"
    singlePlot2 <- plotIndividualTimeProfile(myDc2, plotConfig)
    
    plotGridConfiguration <- createEsqlabsPlotGridConfiguration()
    plotGridConfiguration$title <- "ThisPlotGridHasAVeryLongTitle ThatWillFitOnTopOfThePlots BecauseTLFCanNowWrapTextOnSpaces OrSpecialCharacters"
    plotGridConfiguration$addPlots(list(singlePlot, singlePlot2))
    
    plotGrid(plotGridConfiguration)
```



<sup>Created on 2023-08-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by PavelBal** [comment]
This will definitely reduce the number of scaling required. For use cases as in the example above, I think we should still keep this feature. Example:

Unscaled:
testExport_unscaled

Scaled:
testExport

**Pull request closed without merging**
