### PR TITLE
catch up with `develop` branch

### PR DESCRIPTION
**Pull request by IndrajeetPatil**

### CODE REVIEW

**Comment by PavelBal** [comment]
Lol, I hope this works. Please create a release for this then.

**Comment by IndrajeetPatil** [comment]
It's strange that the first release in the `main` branch is `esqlabsR 1.4.5`, but the version in `develop` branch is lower than that; `esqlabsR 1.2.3`.

What should the new release version be?

**Comment by msevestre** [comment]
The version should be the one from appveyor which is 2.0.38.....
Was the build change to not use appveyor anymore?

**Comment by msevestre** [comment]
https://ci.appveyor.com/project/StephanSchaller/esqlabsr/branch/develop

**Comment by IndrajeetPatil** [comment]
> Was the build change to not use appveyor anymore?

No, we are still using AppVeyor, and I haven't knowingly changed anything about it that should make `{esqlabsR}` behave differently than the other OSPS packages.

I am in general a bit mystified by the versioning schema adopted in OSPS, and I would really appreciate if I can have a call with someone who can walk me through how we are deciding versions and the script that automates this process.

**Comment by IndrajeetPatil** [comment]
> Let's have a chat later today. I'll ping you when I have some time. (90min or so).

Sounds good! Thanks, much appreciated.

**Pull request merged**
