### PR TITLE
upkeep

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
- use `.9000` suffix to mark that this is a development version
- remove spell checking because downloading dependency for spell check is not worth what it's doing
- update documentation (`.Rd` files)
- fix regression in re-export (`%||%` was somehow missing from re-exports)
- remove spurious `OR` entry from pkgdown YAML
- format code in example that is over 120 width and is producing a `NOTE` in checks
- update needed dependencies in README

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
@PavelBal, @msevestre Any ideas what might be happening here?

There is only one test failing because the following code doesn't work:

https://github.com/esqLABS/esqlabsR/blob/83e78c6293b843a621a10bfb476830210b4e35df/tests/testthat/test-utilities-individual.R#L29-L32

The backtrace I see on CI is the following:

```r
Running the tests in 'tests/testthat.R' failed.
Last 13 lines of output:
  Method:  
  Stack trace:
  Backtrace:
      x
   1. \-esqlabsR::readIndividualCharacteristicsFromXLS(...) test-utilities-individual.R:29:2
   2.   \-ospsuite::createIndividualCharacteristics(...)
   3.     \-ospsuite::initPKSim()
   4.       \-rClr::clrCallStatic("PKSim.R.Api", "InitializeOnce")
  
  [ FAIL 1 | WARN 9 | SKIP 0 | PASS 345 ]
  Error: Test failures
  Execution halted
```

**Comment by msevestre** [comment]
I think the version of pksim installed is not compatible with the version of oapsuite-r

(Those two packages need to evolve in //)
What version of oapsuite-r is being used?

**Comment by IndrajeetPatil** [comment]
> What version of oapsuite-r is being used?

`ospsuite 11.0.6`

**Comment by IndrajeetPatil** [comment]
@PavelBal Any ideas on how to get rid of this issue?

**Comment by PavelBal** [comment]
You have to use PK-Sim v11. If it still does not help - let's wait until we merge ospsuiter.

**Comment by msevestre** [comment]
You need to use the latest oapsuite-r compatible with the develop of PKSim

**Comment by IndrajeetPatil** [comment]
Alright, it's working after updating ospsuite version! Thanks!

**Review by PavelBal — APPROVED** [review]

**Pull request merged**
